/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mitre_svmp_events_BaseServer */

#ifndef _Included_org_mitre_svmp_events_StreamHandler
#define _Included_org_mitre_svmp_events_StreamHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef org_mitre_svmp_events_StreamHandler_BUFFER_SIZE
#define org_mitre_svmp_events_StreamHandler_BUFFER_SIZE 8192L



JNIEXPORT jbyteArray JNICALL Java_org_mitre_svmp_events_StreamHandler_getFrameBytesFromNative
(JNIEnv *);

#ifdef __cplusplus
}
#endif
#endif
